name: Testing Action
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executa checkout no repositório 
        uses: actions/checkout@v2
      - name: Exeuctando o deploy
        uses: Obuc/action-deploy-sp@main
        with:
          project: SuperImportante
          url_sp: https://obuc.sharepoint.com/sites/development
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          src_folder: test/
          dst_folder: deploy_test/